Authentication/userApp/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :users, only: [:new , :create]
  resources :places
  resource :sessions, only: [:new , :create , :destroy]

  root 'places#index'
end

Authentication/userApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Authentication/userApp/app/models/place.rb
class Place < ApplicationRecord
    belongs_to :user
end

Authentication/userApp/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :places
end

Authentication/userApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    private 
        def current_user
            user_id = session[:user_id]
            # if user_id
            #     return User.find(user_id)
            # else
            #     return nil
            # end
            user_id && User.find(user_id)
        end
end

Authentication/userApp/app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :require_login, except: [:index]
  before_action :check_ownership, only: [:edit , :update , :destroy]

  def index
    @places = Place.all
  end


  def show 
    @place = Place.find(params[:id])

  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(
      name: params[:place][:name],
      desc: params[:place][:desc])
    @place.user = current_user

    if @place.save
       redirect_to root_url

    else
      render :new
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place && @place.update( name: params[:place][:name],
                               desc: params[:place][:desc],
                               user: current_user)
      redirect_to root_url

    else
      render :edit
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to root_url
  end

  def require_login
    unless  session[:user_id]
      redirect_to new_sessions_url
    end
  end

  def check_ownership
    @place = Place.find(params[:id])

    unless current_user == @place.user
      redirect_to root_url
    end
  end


end

Authentication/userApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        #authenticate the user 
        submitted_email = params[:session][:email] #sree@gmail.com
        submitted_password = params[:session][:password] #qwertyui

        u = User.find_by(email: submitted_email)

        if u && u.authenticate(submitted_password)
            #create a session
            session[:user_id] = u.id 
            redirect_to root_url
        else
            render :new
        end

      
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end
end

Authentication/userApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      redirect_to root_url
    
      
    else
        render :new      
    end
  end
end

Authentication/userApp/app/helpers/application_helper.rb
module ApplicationHelper
end

Authentication/userApp/app/helpers/places_helper.rb
module PlacesHelper
end

Authentication/userApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

Authentication/userApp/app/helpers/users_helper.rb
module UsersHelper
end

Authentication/userApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
<div style="
    padding-top: 20%;
">
    <% if current_user%>
        <%=link_to "logout", sessions_path("current"), method: :delete %>
    <%else%>
        <%= link_to "Sign up", new_users_path%>
        <%= link_to "Log in" , new_sessions_path%>
    <%end%>
    </div>
  </header>
    <%= yield %>
  </body>
</html>

Authentication/userApp/app/views/places/_form.html.erb
<%= form_for @place do |f|%>
<div>
    <%=f.label :name%>
    <%=f.text_field :name%>
</div>

<div>
    <%=f.label :desc%>
    <%=f.text_field :desc%>
</div>



<%= f.submit %>
<% end%>

Authentication/userApp/app/views/places/edit.html.erb
<h1>Create</h1>

<%= render 'form'%>

Authentication/userApp/app/views/places/index.html.erb
<% if @places.count > 0%>
        <% @places.each do | place |%>
            <h3> <%= link_to place.name, place_path(place)%> </h3>
            <p> <%= place.desc%> </p>
        <%end%>
<%else%>

        <p> No places found </p>
<%end%>

<%= link_to "Add place" , new_place_path%>

Authentication/userApp/app/views/places/new.html.erb
<h1>Edit</h1>

<%= render 'form'%>

Authentication/userApp/app/views/places/show.html.erb
<h1><%= @place.name%> </h1>


<%= link_to "Edit", edit_place_path(@place) %>

<%= link_to "Delete", place_path(@place), method: :delete%>

<%= link_to "All places" , places_path %>

Authentication/userApp/app/views/users/new.html.erb
<h1> Sign Up </h1>
<% if @user.errors.any?%>
    <ul>
        <%@user.errors.full_messages.each do |m|%>
        <li> <%= m %>
        </li>
        <%end%>
    </ul>
<%end %>


<%= form_for @user do |f|%>
<div>
    <%=f.label :email%>
    <%=f.email_field :email%>
</div>

<div>
    <%=f.label :password%>
    <%=f.password_field :password%>
</div>

<div>
    <%=f.label :password_confirmation%>
    <%=f.password_field :password_confirmation%>
</div>

<%= f.submit 'Sign Up'%>
<% end%>