photoLab/config/routes.rb
Rails.application.routes.draw do
  root 'photos#index'
  resources :photos do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

photoLab/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :photo
end

photoLab/app/models/photo.rb
class Photo < ApplicationRecord
    has_many :comments #1 : m btw photo and comments 
    has_and_belongs_to_many :tags #m:m btw tags and photos
end

photoLab/app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :photos
end

photoLab/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @photo = Photo.find(params[:photo_id])
        # @comment = Comment.create(name: params[:comment][:name],
        #                         message: params[:comment][:message],
        #                         photo_id: @photo.id)
        @comment = Comment.new(comment_params)
        @comment.photo = @photo #linking the comment with photo
        if @comment.save
        redirect_to photo_url(@photo)
        else
        render :new
        end
    end

    def new
        @photo = Photo.find(params[:photo_id]) #define 
        @comment = Comment.new
    end

    private
    def comment_params
        params.require(:comment).permit(:name, :message)
    end

end

photoLab/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    @comments = @photo.comments
    @tags = @photo.tags
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
   
      if @photo.update(photo_params)
        redirect_to photo_path(@photo)
      else
        render :edit
      end
   
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:title, :url, :desc)
    end
end

photoLab/app/helpers/comments_helper.rb
module CommentsHelper
end

photoLab/app/helpers/photos_helper.rb
module PhotosHelper
end

photoLab/app/views/comments/_form.html.erb
<%= form_for [@photo, @comment] do |form| %>
 
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

photoLab/app/views/comments/new.html.erb
<%= render partial: "form"%>

photoLab/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'http://fonts.googleapis.com/css?family=Poiret+One|Lora' %>
  </head>

  <body>

    <header>
      <h1><%= link_to 'Photogur', root_path %></h1>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

photoLab/app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

photoLab/app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

photoLab/app/views/photos/index.html.erb
<%= link_to "Add new photo", new_photo_path %>

<section class="photos">
  <% @photos.each do |photo| %>
    <section class="photo">
      <p> <%= link_to 'View', photo_path(photo) %> <%= link_to 'Edit', edit_photo_path(photo) %> <%= link_to 'Delete', photo_path(photo), method: :delete, data: {confirm: "Are you sure?" } %> </p>
      <p class="photo-title"> <%= photo.title %> </p>
      <p class="description"> <%= photo.desc %> </p>
      <div class="image-frame"><%= link_to image_tag(photo.url), photo_path(photo) %></div>
      <p> Comments :: <%=photo.comments.count %></p>
    </section>
  <% end %>
</section>

photoLab/app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

photoLab/app/views/photos/show.html.erb
<section class="show-photo">
  <p> <%= link_to 'Edit', edit_photo_path(@photo) %> <%= link_to 'Delete', photo_path(@photo), method: :delete, data: {confirm: "Are you sure?" } %> </p>
  <p> <%= @photo.title %> </p>
  <p> <%= @photo.desc %> </p>
  <%= image_tag @photo.url %>
</section>


<h2>Tags </h2>

<ul>
 <% @tags.each do |tag|%>
  <li>
    <p><%=tag.name %> </p>

  </li>
 <% end %>
</ul>

<h2>Comments </h2>
<p><%=link_to 'Add  Comments' ,new_photo_comment_path(@photo) %></p>
<ul>
 <% @comments.each do |comment|%>
  <li>
    <p>On <%= comment.created_at%> <%=comment.name %> </p>
    <p> <%=comment.message%> </p>
  </li>
 <% end %>
</ul>